// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varga_Balázs_Ádám_backend;

#nullable disable

namespace Varga_Balázs_Ádám_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230529140510_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Varga_Balázs_Ádám_backend.Models.Ingatlan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ar")
                        .HasColumnType("int");

                    b.Property<DateTime>("hirdetesDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("kategoriaid")
                        .HasColumnType("int");

                    b.Property<string>("kepUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("tehermentes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("kategoriaid");

                    b.ToTable("ingatlanok");
                });

            modelBuilder.Entity("Varga_Balázs_Ádám_backend.Models.Kategoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("kategoriak");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nev = "Ház"
                        },
                        new
                        {
                            id = 2,
                            nev = "Lakás"
                        },
                        new
                        {
                            id = 3,
                            nev = "Építési telek"
                        },
                        new
                        {
                            id = 4,
                            nev = "Garázs"
                        },
                        new
                        {
                            id = 5,
                            nev = "Mezőgazdasági terület"
                        },
                        new
                        {
                            id = 6,
                            nev = "Ipari ingatlan"
                        });
                });

            modelBuilder.Entity("Varga_Balázs_Ádám_backend.Models.Ingatlan", b =>
                {
                    b.HasOne("Varga_Balázs_Ádám_backend.Models.Kategoria", "kategoria")
                        .WithMany()
                        .HasForeignKey("kategoriaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
